name: first workflow

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Type of load'
        required: true
        default: 'smoke'
        type: choice
        options:
          - smoke
          - stress
    
jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: print hello
      run: |
          echo "hello there - first output"
          echo "How are you doing -second output"
          echo "Type of load: $LEVEL"
      env:
          LEVEL: ${{ inputs.logLevel }}
