name: Greetings

on: [push, workflow_dispatch]

jobs:
  runjob:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
